sudo: required
before_install:
  - sudo update-ca-certificates

language: ruby
rvm:
  2.3.3

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --assume-extension --url-ignore "#" ./_site
