url: http://www.cowosedlice.cz
baseurl:

# Site settings
title: Cowosedlice.cz - sdílená kancelář v Novosedlicích u Teplic
title-visible: COWOSEDLICE
email: radek@cowosedlice.cz
description: "Cowosedlice jsou tu pro ty, kterým nevyhovuje práce z domova anebo pro ty, kteří zkrátka jen chtějí zkusit změnu."

# About section
history-heading: Cowosedlické vybavení
history-subheading: 
history:
- title: Připojení k internetu
  pic: internet
  descr: Přípojka do sítě jede na vyhrazených linkách od dvou na sobě nezávislých poskytovatelů v rychlostech 50/25 a 30/10. Na Novosedlice dobrý.

- title: Vlastní místo pro stálé členy
  pic: stul
  descr: Stálí členové mají své vlastní místo 24/7 a mohou se tu trochu zahnízdit.

- title: Káva od Frolíka
  pic: kava
  descr: Neomezené množství kávy pro každého - stačí vzít hrneček a zmáčknout čudlík. Je to pohodlné a dost návykové.

- title: Kuchyňský koutek
  pic: kuchyn
  descr: Kachnu sice neupečeme, ale pro béžně potřeby ajťáků kuchyň plně dostačuje - lednice, mikrovlnka, rychlovarná konvice atd.

- title: Kam na oběd?
  pic: pizza
  descr: Hned vedle jsou hotovky od Plemanářů, 8 minut chůze vyhlášená Pizzeria Sluis a jako nouzovka tu funguje i DámeJídlo. 

- title: Možnosti dopravy
  pic: doprava
  descr: Autem lze zaparkovat hned u coworkingu, pro ty s lítačkou jezdí autobusy č. 491, 492, 494, 482, 481, 802 a pokud přijedete na kole, máme suchý uzamykatelný průjezd.

# Price list
price-heading: Ceník
price-subheading: Ať už máte malý nebo velký tarif, vždy budete mít možnost využívat všeho, co se v cowosedlicích nachází. Wifi, tiskárna, cowosedlické PC, kuchyňka, lednice, kávovar atd. A stálí členové mají samozřejmě své vlastní vyhrazené pracovní místo.
price:
- tariff: 210Kč denně
  pic: battery-quarter
  desc-title: Malý tarif
  desc: Pro nové členy jsou 2 dny zdarma, jinak 210Kč za každý započatý den.

- tariff: 1540Kč měsíčně
  pic: battery-three-quarters
  desc-title: Střední tarif
  desc: Pokrývá 10 pracovních dní od 8:00 do 17:00 a můžete pracovat tam, kde je zrovna volno.

- tariff: 2450Kč měsíčně
  pic: battery-full
  desc-title: Velký tarif
  desc: Přístup 24/7 a možnost zřízení vlastního pracovního místa.  
# Team names, titles and social links
people-heading: Aktivní členové
people-subheading: Reálně se v Novosedlicích potkáme 2 až 3. Těsno nám zatím není a budeme samozřejmě rádi za každého nového člena.
people:
- name: Radek Novák
  pic: 1
  position: Řeší věci související s webgames.cz - tvorba obsahu, programování (php, nette, javascript, mysql), seo, analytika, prodej reklamy atd.
  social:
    - title: gamepad
      url: http://www.webgames.cz/kontakt
    - title: link
      url: http://www.lptube.cz
    - title: facebook
      url: https://www.facebook.com/radek.novak.75

- name: Radim Klaška
  pic: 2
  position: Drupal vývojář pro australský Morpht Pty. Ltd. a pro český Drupal.cz + fanda do všeho, co má jedničky a nuly.
  social:
    - title: twitter
      url: https://twitter.com/radimklaska
    - title: tint
      url: https://www.drupal.org/u/radimklaska
    - title: code-fork
      url: https://github.com/radimklaska

- name: Honza Pára
  pic: 3
  position: Drupalista na volné noze, kodér šablon, site builder, barista samouk, motorkář a herec teplického divadla.
  social:
    - title: tint
      url: https://www.drupal.org/u/honzapara
    - title: code-fork
      url: https://github.com/honzapara


- name: Jan Nedvěd
  pic: 4
  position: Projektant ocelových konstrukcí na volné noze.
  social:
    - title: facebook
      url: https://www.facebook.com/johny.nedved


- name: Volné místo
  pic: 999
  position: Ještě máme pár volných míst. 
  social:
    - title: plus
      url: mailto:radek@cowosedlice.cz


- name: Volné místo
  pic: 999
  position: Ještě máme pár volných míst. 
  social:
    - title: plus
      url: mailto:radek@cowosedlice.cz


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: link
    url: http://www.cowosedlice.cz/
  - title: facebook
    url: https://www.facebook.com/cowosedlice/
  - title: github
    url: https://github.com/cowosedlice

# Postal address (add as many lines as necessary)
address:
  - line: Míru 218
  - line: Novosedlice, 417 31

# Build settings
markdown: kramdown
permalink: pretty

