url: http://www.cowosedlice.cz
baseurl:

# Site settings
title: Cowosedlice.cz - sdílená kancelář v Novosedlicích u Teplic
title-visible: COWOSEDLICE
email: radek@cowosedlice.cz
description: "Coworkingová kancelář Novosedlice / Teplice."

# About section
history-heading: Trocha historie
history-subheading: O coworkingové kanceláři v Teplicích jsme přemýšleli pár let. Ovšem cesta od myšlenky ke skutečné realizaci chvílí trvala :).
history:
- date: červen 2014
  title: Řempo
  pic: rempo_start
  descr: První kancelář byla malá, rozbitá ale levná.

- date: září 2014
  title: Fungujeme!
  pic: rempo_ready
  descr: Mini kancelář v areálu Řempa jsme si opravili a začali fungovat.

- date: 2015
  title: Rosteme
  pic: nb
  descr: Časem se k nám pridávají Petr, Honza a Jirka a místo přestává stačit.

- date: leden 2016
  title: Stěhujeme se.
  pic: stehovani
  descr: Máme dostatek místa pro nové kolegy a navíc pěkné zázemí.

- date: červen 2016
  title: Kávovar
  pic: kavovar
  descr: Pořízení kavalitního kávovaru bylo zlomovým bodem. Pohodlí a produktivita se mnohonásobně zlepšily.

- date: srpen 2016
  title: Cowosedlice.cz
  pic: web
  descr: Oficiální otevření na nové adrese.
history-cta1: Napiš
history-cta2: Přijď
history-cta3: Přidej se!

# Price list
price-heading: Ceník
price-subheading: Ať už máte malý nebo velký tarif, vždy budete mít možnost využívat všeho, co se v cowosedlicích nachází.
price:
- tariff: 1750Kč měsíčně
  pic: battery-full
  desc-title: Velký tarif
  desc: Přístup 24/7 a možnost zřízení vlastního pracovního místa.

- tariff: 1100Kč měsíčně
  pic: battery-three-quarters
  desc-title: Střední tarif
  desc: Pokrývá 10 pracovních dní od 8:00 do 17:00 a můžete pracovat tam, kde je zrovna volno.
  
- tariff: 150 za každý den
  pic: battery-quarter
  desc-title: Malý tarif
  desc: Přístup v pracovní době mezi 8:00 a 17:00.

# Team names, titles and social links
people-heading: Aktivní členové
people-subheading: Alfou a omegou každého coworkingu jsou hlavně samotní lidé, finanční úspora v porovnání s vlastní kanceláří je jen příjemnný vedlejší bonus :). 
people:
- name: Ing. Radek Novák
  pic: 1
  position: Řeší věci související s webgames.cz - tvorba obsahu, programování (php, nette, javascript, mysql), seo, analytika, prodej reklamy atd.
  social:
    - title: gamepad
      url: http://www.webgames.cz/kontakt
    - title: link
      url: http://www.lptube.cz
    - title: facebook
      url: https://www.facebook.com/radek.novak.75

- name: Bc. Radim Klaška
  pic: 2
  position: Drupal vývojář pro australský Morpht Pty. Ltd. a pro český Drupal.cz + fanda do všeho, co má jedničky a nuly.
  social:
    - title: twitter
      url: https://twitter.com/radimklaska
    - title: tint
      url: https://www.drupal.org/u/radimklaska
    - title: code-fork
      url: https://github.com/radimklaska

- name: Honza Pára
  pic: 3
  position: Drupalista na volné noze, kodér šablon, site builder, barista samouk, motorkář a herec teplického divadla.
  social:
    - title: tint
      url: https://www.drupal.org/u/honzapara
    - title: code-fork
      url: https://github.com/honzapara

- name: Jiří Šmíd
  pic: 4
  position: Tvorba webových stránek, grafiky, html šablon, SEO optimalizace a certifikovaný Google Street View fotograf zajišťující virtuální prohlídky.
  social:
    - title: link
      url: http://www.jirismid.cz
    - title: link
      url: http://www.prohlidka-virtualne.cz/     
    - title: code-fork
      url: https://github.com/jirismid

- name: Martin Čapek
  pic: 5
  position: Majitel e-shopu s dětskou výživou nutrilonstore.com.
  social:
    - title: link
      url: http://nutrilonstore.com/en/
    - title: facebook
      url: https://www.facebook.com/mcapek

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: link
    url: http://www.cowosedlice.cz/
  - title: facebook
    url: https://www.facebook.com/cowosedlice/
  - title: github
    url: https://github.com/cowosedlice

# Postal address (add as many lines as necessary)
address:
  - line: Míru 218
  - line: Novosedlice, 417 31

# Build settings
markdown: kramdown
permalink: pretty
