url: https://cowosedlice.cz
baseurl:

# Site settings
title: Cowosedlice.cz
email: radek@cowosedlice.cz
description: "Coworkingová kancelář Novosedlice / Teplice."

# About section
history-heading: O nás
history-subheading: Lorem ipsum dolor sit amet consectetur.
history:
- date: 2013
  title: Řempo!
  pic: 1
  descr: Lorem ipsum dolor sit amet, consectetur ad

- date: 2014
  title: Muhehe
  pic: 2
  descr: Lorem ipsum dolor sit amet, consectetur ad

- date: 2015
  title: Muhehe
  pic: 3
  descr: Lorem ipsum dolor sit amet, consectetur ad

- date: 2016
  title: Muhehe
  pic: 4
  descr: Lorem ipsum dolor sit amet, consectetur ad
history-cta1: Napiš,
history-cta2: přijď.
history-cta3: Přidej se!,

# Team names, titles and social links
people:
- name: Radek Novák
  pic: 1
  position: Lead Designer
  social:
    - title: gamepad
      url: http://www.webgames.cz/kontakt/
    - title: code-fork
      url: https://github.com/radektp

- name: Radim Klaška
  pic: 2
  position: Drupal developer @ Morpht Pty. Ltd. & Drupal.cz
  social:
    - title: twitter
      url: https://twitter.com/radimklaska
    - title: tint
      url: https://www.drupal.org/u/radimklaska
    - title: code-fork
      url: https://github.com/radimklaska

- name: Honza Páza
  pic: 3
  position: Lead Developer
  social:
    - title: code-fork
      url: https://github.com/honzapara

- name: Jiří Šmíd
  pic: 4
  position: Lead Developer
  social:
    - title: code-fork
      url: https://github.com/jirismid

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Míru 218
  - line: Novosedlice, 417 31

# Build settings
markdown: kramdown
permalink: pretty
